--DROP TABLE

DROP TABLE USER_DATA;
DROP TABLE ROOM_DATA;
DROP TABLE ROOM_TYPE;
DROP TABLE RESERVATION_LIST;
DROP TABLE PAY_LIST;
DROP TABLE REVIEW_LIST;
DROP TABLE WISH_LIST;

--------------------------------------------------------------------------------
--CREATE TABLES

CREATE TABLE USER_DATA (
	user_No	NUMBER(3) CONSTRAINT PK_USER_DATA PRIMARY KEY,
    user_Name VARCHAR2(20) NOT NULL,
	user_Id	VARCHAR2(20) NOT NULL,
	pw	VARCHAR2(20) NOT NULL,
	ssn	VARCHAR2(14) NOT NULL,
	tel	VARCHAR2(14) NOT NULL
);

CREATE TABLE ROOM_TYPE(
    room_Type_No NUMBER(3) CONSTRAINT PK_ROOM_TYPE PRIMARY KEY,
    room_Type VARCHAR2(30) NOT NULL ----´õºí·ë/ÇÁ¸®¹Ì¾î ´õºí·ë/½ºÀ§Æ® ´õºí·ë/ Æ®À©·ë/ÇÁ¸®¹Ì¾î Æ®À©·ë/½ºÀ§Æ® Æ®À©·ë
);


CREATE TABLE ROOM_DATA (
	room_No	NUMBER(3) CONSTRAINT PK_ROOM_DATA PRIMARY KEY,
	room_Type_No NUMBER(3) NOT NULL, 
	room_Size	NUMBER NOT NULL, --39/43/68/  /39/43/52
	price	NUMBER NOT NULL, --459,800/496,100/1,173,700    459,800/496,100/617,100
	floor	NUMBER(10) NOT NULL, --  87~101Ãþ 87~93Ãþ
	aprpr_Nmb_pp	NUMBER(3) NOT NULL, --2~5
	number_Beds	NUMBER(2) NOT NULL, --1~3
	breakfast_Status	VARCHAR2(15) NOT NULL, --YES OR NO
	prc_adPrsn	NUMBER NOT NULL, -- 100,000 / 200,000 / 300,000
	avg_score NUMBER(2,1) CHECK (AVG_SCORE BETWEEN 1 AND 5),
    FOREIGN KEY(room_Type_No) REFERENCES ROOM_TYPE(room_Type_No)
);


CREATE TABLE RESERVATION_LIST (
	reser_No	number CONSTRAINT PK_RESERVATION_LIST PRIMARY KEY,
	reser_Date	DATE NOT NULL,
	user_No	NUMBER(3) NOT NULL,
	checkin_Date	DATE NOT NULL,
	checkout_Date	DATE NOT NULL,
	total_people_Num	NUMBER(2) NOT NULL,
	total_Price	NUMBER NOT NULL,
	room_No	NUMBER(3) NOT NULL,
    FOREIGN KEY(user_No) REFERENCES USER_DATA(user_No),
    FOREIGN KEY(room_No) REFERENCES ROOM_DATA(room_No)
    
);


CREATE TABLE PAY_LIST (
	pay_No	number CONSTRAINT PK_PAY_LIST PRIMARY KEY,
	pay_Date	date NOT NULL,
	reser_No	number NOT NULL,
    FOREIGN KEY(reser_No) REFERENCES RESERVATION_LIST(reser_No)
);

CREATE TABLE REVIEW_LIST (
	review_No number CONSTRAINT PK_REVIEW_LIST PRIMARY KEY,
	user_No	NUMBER(3) NOT NULL,
	room_No	NUMBER(3) NOT NULL,
	score	NUMBER(1) NOT NULL,
	review_Content	VARCHAR(2000) NOT NULL,
	review_Date	DATE NOT NULL,
    FOREIGN KEY(user_No) REFERENCES USER_DATA(user_No),
    FOREIGN KEY(room_No) REFERENCES ROOM_DATA(room_No)
);


CREATE TABLE WISH_LIST (
	wish_No	number CONSTRAINT PK_WISH_LIST PRIMARY KEY,
	user_No	NUMBER(3) NOT NULL,
	room_No	NUMBER(3) NOT NULL,
	wish_Date	DATE NOT NULL,
    FOREIGN KEY(user_No) REFERENCES USER_DATA(user_No),
    FOREIGN KEY(room_No) REFERENCES ROOM_DATA(room_No)
);
--------------------------------------------------------------------------------
--CREATE SEQUENCE

CREATE SEQUENCE USER_DATA_NO_SEQ  NOCACHE;
CREATE SEQUENCE ROOM_DATA_NO_SEQ  NOCACHE;
CREATE SEQUENCE ROOM_TYPE_NO_SEQ  NOCACHE;
CREATE SEQUENCE RESERVATION_LIST_NO_SEQ  NOCACHE;
CREATE SEQUENCE PAY_LIST_NO_SEQ  NOCACHE;
CREATE SEQUENCE REVIEW_LIST_NO_SEQ  NOCACHE;
CREATE SEQUENCE WISH_LIST_NO_SEQ  NOCACHE;



